import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/providers/auth-provider';
import CartContextProvider from '@/providers/cart-provider';
import WishlistContextProvider from '@/providers/wishlist-provider';
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <WishlistContextProvider>
              <Navbar />
              {children}
              <Toaster richColors position="top-right" />
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
